[general]

  log_level = 4

[postgresql]

  # the postgres DB dsn
  dsn="postgres://smart_ac:password@localhost/smart_ac?sslmode=disable"
  # should the application run migrations on startup
  automigrate=true

[external_api]
  # ip:port to bind the (user facing) http server to (web-interface and REST / gRPC api)  
  bind="0.0.0.0:8080"

  # http server TLS certificate (optional)
  tls_cert=""

  # http server TLS key (optional)
  tls_key=""

  # JWT secret used for api authentication / authorization
  jwt_secret="RiaTH7YRNYBF1Zdj0dHAul7xx8FEujRh1GenrzteqJ0="