// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datum.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// How a datum to be presented to the UI looks like.
type GetDatumResponse struct {
	// Datum ID.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Device ID.
	DeviceId int64 `protobuf:"varint,2,opt,name=device_id,json=deviceID,proto3" json:"device_id,omitempty"`
	// Temperature as a float64.
	Temperature float64 `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Carbon monoxide as a float 64.
	CarbonMonoxide float64 `protobuf:"fixed64,4,opt,name=carbon_monoxide,json=carbonMonoxide,proto3" json:"carbon_monoxide,omitempty"`
	// Air humidity percentage as a float64 between 0.0 and 1.0 included.
	AirHumidity float64 `protobuf:"fixed64,5,opt,name=air_humidity,json=airHumidity,proto3" json:"air_humidity,omitempty"`
	// UTF8 string of max 149 characters.
	HealthStatus string `protobuf:"bytes,6,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	// Created at timestamp.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The device's serial number.
	SerialNumber         string   `protobuf:"bytes,8,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDatumResponse) Reset()         { *m = GetDatumResponse{} }
func (m *GetDatumResponse) String() string { return proto.CompactTextString(m) }
func (*GetDatumResponse) ProtoMessage()    {}
func (*GetDatumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{0}
}
func (m *GetDatumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDatumResponse.Unmarshal(m, b)
}
func (m *GetDatumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDatumResponse.Marshal(b, m, deterministic)
}
func (dst *GetDatumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDatumResponse.Merge(dst, src)
}
func (m *GetDatumResponse) XXX_Size() int {
	return xxx_messageInfo_GetDatumResponse.Size(m)
}
func (m *GetDatumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDatumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDatumResponse proto.InternalMessageInfo

func (m *GetDatumResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetDatumResponse) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *GetDatumResponse) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *GetDatumResponse) GetCarbonMonoxide() float64 {
	if m != nil {
		return m.CarbonMonoxide
	}
	return 0
}

func (m *GetDatumResponse) GetAirHumidity() float64 {
	if m != nil {
		return m.AirHumidity
	}
	return 0
}

func (m *GetDatumResponse) GetHealthStatus() string {
	if m != nil {
		return m.HealthStatus
	}
	return ""
}

func (m *GetDatumResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetDatumResponse) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

// How a datum sent by a device looks like.
type Datum struct {
	// Temperature as a float64.
	Temperature float64 `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Carbon monoxide as a float 64.
	CarbonMonoxide float64 `protobuf:"fixed64,3,opt,name=carbon_monoxide,json=carbonMonoxide,proto3" json:"carbon_monoxide,omitempty"`
	// Air humidity percentage as a float64 between 0.0 and 1.0 included.
	AirHumidity float64 `protobuf:"fixed64,4,opt,name=air_humidity,json=airHumidity,proto3" json:"air_humidity,omitempty"`
	// UTF8 string of max 149 characters.
	HealthStatus         string   `protobuf:"bytes,5,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Datum) Reset()         { *m = Datum{} }
func (m *Datum) String() string { return proto.CompactTextString(m) }
func (*Datum) ProtoMessage()    {}
func (*Datum) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{1}
}
func (m *Datum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum.Unmarshal(m, b)
}
func (m *Datum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum.Marshal(b, m, deterministic)
}
func (dst *Datum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum.Merge(dst, src)
}
func (m *Datum) XXX_Size() int {
	return xxx_messageInfo_Datum.Size(m)
}
func (m *Datum) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum.DiscardUnknown(m)
}

var xxx_messageInfo_Datum proto.InternalMessageInfo

func (m *Datum) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Datum) GetCarbonMonoxide() float64 {
	if m != nil {
		return m.CarbonMonoxide
	}
	return 0
}

func (m *Datum) GetAirHumidity() float64 {
	if m != nil {
		return m.AirHumidity
	}
	return 0
}

func (m *Datum) GetHealthStatus() string {
	if m != nil {
		return m.HealthStatus
	}
	return ""
}

// To create data a device must send a request with it's serial number and the array of data.
type CreateDataRequest struct {
	// Device's serial number.
	SerialNumber string `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// Array of data.
	Data                 []*Datum `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDataRequest) Reset()         { *m = CreateDataRequest{} }
func (m *CreateDataRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDataRequest) ProtoMessage()    {}
func (*CreateDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{2}
}
func (m *CreateDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDataRequest.Unmarshal(m, b)
}
func (m *CreateDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDataRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDataRequest.Merge(dst, src)
}
func (m *CreateDataRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDataRequest.Size(m)
}
func (m *CreateDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDataRequest proto.InternalMessageInfo

func (m *CreateDataRequest) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *CreateDataRequest) GetData() []*Datum {
	if m != nil {
		return m.Data
	}
	return nil
}

// Request a datum by id.
type DatumRequest struct {
	// The datum's id.
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatumRequest) Reset()         { *m = DatumRequest{} }
func (m *DatumRequest) String() string { return proto.CompactTextString(m) }
func (*DatumRequest) ProtoMessage()    {}
func (*DatumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{3}
}
func (m *DatumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatumRequest.Unmarshal(m, b)
}
func (m *DatumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatumRequest.Marshal(b, m, deterministic)
}
func (dst *DatumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatumRequest.Merge(dst, src)
}
func (m *DatumRequest) XXX_Size() int {
	return xxx_messageInfo_DatumRequest.Size(m)
}
func (m *DatumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatumRequest proto.InternalMessageInfo

func (m *DatumRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Request all data between 2 dates, with limit and offset.
type ListDataRequest struct {
	// Max amount of data to retrieve.
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset for retrieving data.
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Start date.
	StartDate *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// End date.
	EndDate *timestamp.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// Filters is an array of sensor types. Valid values are: temperature, carbon_monoxide, air_humidity, health_status.
	// For any sensor type not included in filters, the zero value (empty string for health status, 0.0 for the others) will be returned.
	Filters              []string `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDataRequest) Reset()         { *m = ListDataRequest{} }
func (m *ListDataRequest) String() string { return proto.CompactTextString(m) }
func (*ListDataRequest) ProtoMessage()    {}
func (*ListDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{4}
}
func (m *ListDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDataRequest.Unmarshal(m, b)
}
func (m *ListDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDataRequest.Marshal(b, m, deterministic)
}
func (dst *ListDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDataRequest.Merge(dst, src)
}
func (m *ListDataRequest) XXX_Size() int {
	return xxx_messageInfo_ListDataRequest.Size(m)
}
func (m *ListDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDataRequest proto.InternalMessageInfo

func (m *ListDataRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListDataRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListDataRequest) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *ListDataRequest) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *ListDataRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

// Request all data for a given device between 2 dates, with limit and offset.
type ListDataForDeviceRequest struct {
	DeviceId int64 `protobuf:"varint,1,opt,name=device_id,proto3" json:"device_id,omitempty"`
	// Max amount of data to retrieve.
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset for retrieving data.
	Offset int64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Start date.
	StartDate *timestamp.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// End date.
	EndDate *timestamp.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// Filters is an array of values to request. Valid values are: temperature, carbon_monoxide, air_humidity, health_status.
	// For any value not included in filters, the zero value (empty string for health status, 0.0 for the others) will be returned.
	Filters              []string `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDataForDeviceRequest) Reset()         { *m = ListDataForDeviceRequest{} }
func (m *ListDataForDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*ListDataForDeviceRequest) ProtoMessage()    {}
func (*ListDataForDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{5}
}
func (m *ListDataForDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDataForDeviceRequest.Unmarshal(m, b)
}
func (m *ListDataForDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDataForDeviceRequest.Marshal(b, m, deterministic)
}
func (dst *ListDataForDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDataForDeviceRequest.Merge(dst, src)
}
func (m *ListDataForDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_ListDataForDeviceRequest.Size(m)
}
func (m *ListDataForDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDataForDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDataForDeviceRequest proto.InternalMessageInfo

func (m *ListDataForDeviceRequest) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *ListDataForDeviceRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListDataForDeviceRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListDataForDeviceRequest) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *ListDataForDeviceRequest) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *ListDataForDeviceRequest) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

//
type ListDataResponse struct {
	// Total amount of data available.
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// The data returned following the request's restrictions.
	Result               []*GetDatumResponse `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListDataResponse) Reset()         { *m = ListDataResponse{} }
func (m *ListDataResponse) String() string { return proto.CompactTextString(m) }
func (*ListDataResponse) ProtoMessage()    {}
func (*ListDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_datum_6d867942def1b149, []int{6}
}
func (m *ListDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDataResponse.Unmarshal(m, b)
}
func (m *ListDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDataResponse.Marshal(b, m, deterministic)
}
func (dst *ListDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDataResponse.Merge(dst, src)
}
func (m *ListDataResponse) XXX_Size() int {
	return xxx_messageInfo_ListDataResponse.Size(m)
}
func (m *ListDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDataResponse proto.InternalMessageInfo

func (m *ListDataResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListDataResponse) GetResult() []*GetDatumResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDatumResponse)(nil), "api.GetDatumResponse")
	proto.RegisterType((*Datum)(nil), "api.Datum")
	proto.RegisterType((*CreateDataRequest)(nil), "api.CreateDataRequest")
	proto.RegisterType((*DatumRequest)(nil), "api.DatumRequest")
	proto.RegisterType((*ListDataRequest)(nil), "api.ListDataRequest")
	proto.RegisterType((*ListDataForDeviceRequest)(nil), "api.ListDataForDeviceRequest")
	proto.RegisterType((*ListDataResponse)(nil), "api.ListDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatumServiceClient is the client API for DatumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatumServiceClient interface {
	// Create creates the given datum.
	Create(ctx context.Context, in *CreateDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get returns the datum matching the given id.
	Get(ctx context.Context, in *DatumRequest, opts ...grpc.CallOption) (*GetDatumResponse, error)
	// List returns the available data.
	List(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (*ListDataResponse, error)
	// ListForDevice returns the available data for a given device id.
	ListForDevice(ctx context.Context, in *ListDataForDeviceRequest, opts ...grpc.CallOption) (*ListDataResponse, error)
	// Delete deletes the datum matching the given id.
	Delete(ctx context.Context, in *DatumRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type datumServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatumServiceClient(cc *grpc.ClientConn) DatumServiceClient {
	return &datumServiceClient{cc}
}

func (c *datumServiceClient) Create(ctx context.Context, in *CreateDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.DatumService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumServiceClient) Get(ctx context.Context, in *DatumRequest, opts ...grpc.CallOption) (*GetDatumResponse, error) {
	out := new(GetDatumResponse)
	err := c.cc.Invoke(ctx, "/api.DatumService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumServiceClient) List(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (*ListDataResponse, error) {
	out := new(ListDataResponse)
	err := c.cc.Invoke(ctx, "/api.DatumService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumServiceClient) ListForDevice(ctx context.Context, in *ListDataForDeviceRequest, opts ...grpc.CallOption) (*ListDataResponse, error) {
	out := new(ListDataResponse)
	err := c.cc.Invoke(ctx, "/api.DatumService/ListForDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumServiceClient) Delete(ctx context.Context, in *DatumRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.DatumService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatumServiceServer is the server API for DatumService service.
type DatumServiceServer interface {
	// Create creates the given datum.
	Create(context.Context, *CreateDataRequest) (*empty.Empty, error)
	// Get returns the datum matching the given id.
	Get(context.Context, *DatumRequest) (*GetDatumResponse, error)
	// List returns the available data.
	List(context.Context, *ListDataRequest) (*ListDataResponse, error)
	// ListForDevice returns the available data for a given device id.
	ListForDevice(context.Context, *ListDataForDeviceRequest) (*ListDataResponse, error)
	// Delete deletes the datum matching the given id.
	Delete(context.Context, *DatumRequest) (*empty.Empty, error)
}

func RegisterDatumServiceServer(s *grpc.Server, srv DatumServiceServer) {
	s.RegisterService(&_DatumService_serviceDesc, srv)
}

func _DatumService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatumService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServiceServer).Create(ctx, req.(*CreateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatumService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatumService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServiceServer).Get(ctx, req.(*DatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatumService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatumService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServiceServer).List(ctx, req.(*ListDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatumService_ListForDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataForDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServiceServer).ListForDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatumService/ListForDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServiceServer).ListForDevice(ctx, req.(*ListDataForDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatumService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatumService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServiceServer).Delete(ctx, req.(*DatumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DatumService",
	HandlerType: (*DatumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DatumService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DatumService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DatumService_List_Handler,
		},
		{
			MethodName: "ListForDevice",
			Handler:    _DatumService_ListForDevice_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DatumService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datum.proto",
}

func init() { proto.RegisterFile("datum.proto", fileDescriptor_datum_6d867942def1b149) }

var fileDescriptor_datum_6d867942def1b149 = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x18, 0x95, 0xed, 0x24, 0x6d, 0xbe, 0xb4, 0x69, 0x3b, 0xea, 0x8d, 0xac, 0xf4, 0x2f, 0xd7, 0x57,
	0x57, 0x37, 0xaa, 0x74, 0x13, 0xa9, 0x88, 0x05, 0xec, 0x50, 0x43, 0x0b, 0x02, 0xba, 0x70, 0x59,
	0xb0, 0xb3, 0x26, 0xf1, 0x97, 0x76, 0x24, 0xff, 0x61, 0x7f, 0x46, 0x54, 0x55, 0x37, 0xbc, 0x02,
	0x3b, 0x1e, 0x81, 0x25, 0xaf, 0xc1, 0x92, 0x57, 0xe0, 0x09, 0x78, 0x02, 0xe4, 0x99, 0x49, 0x93,
	0x3a, 0x29, 0xad, 0xba, 0x9c, 0xe3, 0xf3, 0x9d, 0x99, 0x73, 0xe6, 0x78, 0xa0, 0xe1, 0x73, 0xca,
	0xc3, 0x5e, 0x92, 0xc6, 0x14, 0x33, 0x8b, 0x27, 0xa2, 0xbd, 0x7d, 0x16, 0xc7, 0x67, 0x01, 0xf6,
	0x79, 0x22, 0xfa, 0x3c, 0x8a, 0x62, 0xe2, 0x24, 0xe2, 0x28, 0x53, 0x94, 0xf6, 0x9e, 0xfe, 0x2a,
	0x57, 0xc3, 0x7c, 0xdc, 0x27, 0x11, 0x62, 0x46, 0x3c, 0x4c, 0x34, 0x61, 0xab, 0x4c, 0xc0, 0x30,
	0xa1, 0x0b, 0xf5, 0xd1, 0xf9, 0x66, 0xc2, 0xfa, 0x31, 0xd2, 0xa0, 0xd8, 0xd3, 0xc5, 0x2c, 0x89,
	0xa3, 0x0c, 0x59, 0x13, 0x4c, 0xe1, 0xdb, 0x46, 0xc7, 0xe8, 0x5a, 0xae, 0x29, 0x7c, 0xb6, 0x05,
	0x75, 0x1f, 0x3f, 0x88, 0x11, 0x7a, 0xc2, 0xb7, 0x4d, 0x09, 0x2f, 0x2b, 0xe0, 0xe5, 0x80, 0x75,
	0xa0, 0x41, 0x18, 0x26, 0x98, 0x72, 0xca, 0x53, 0xb4, 0xad, 0x8e, 0xd1, 0x35, 0xdc, 0x59, 0x88,
	0xfd, 0x07, 0x6b, 0x23, 0x9e, 0x0e, 0xe3, 0xc8, 0x0b, 0xe3, 0x28, 0xfe, 0x28, 0x7c, 0xb4, 0x2b,
	0x92, 0xd5, 0x54, 0xf0, 0x1b, 0x8d, 0xb2, 0xbf, 0x61, 0x85, 0x8b, 0xd4, 0x3b, 0xcf, 0x43, 0xe1,
	0x0b, 0xba, 0xb0, 0xab, 0x4a, 0x8b, 0x8b, 0xf4, 0x85, 0x86, 0xd8, 0x3f, 0xb0, 0x7a, 0x8e, 0x3c,
	0xa0, 0x73, 0x2f, 0x23, 0x4e, 0x79, 0x66, 0xd7, 0x3a, 0x46, 0xb7, 0xee, 0xae, 0x28, 0xf0, 0x54,
	0x62, 0xec, 0x09, 0xc0, 0x28, 0x45, 0x4e, 0xe8, 0x7b, 0x9c, 0xec, 0xa5, 0x8e, 0xd1, 0x6d, 0x1c,
	0xb4, 0x7b, 0x2a, 0x86, 0xde, 0x24, 0x86, 0xde, 0xdb, 0x49, 0x4e, 0x6e, 0x5d, 0xb3, 0x9f, 0x51,
	0xa1, 0x9f, 0x61, 0x2a, 0x78, 0xe0, 0x45, 0x79, 0x38, 0xc4, 0xd4, 0x5e, 0x56, 0xfa, 0x0a, 0x3c,
	0x91, 0x98, 0xf3, 0xc5, 0x80, 0xaa, 0x4c, 0xac, 0x6c, 0xde, 0xbc, 0x97, 0x79, 0xeb, 0x5e, 0xe6,
	0x2b, 0xf7, 0x30, 0x5f, 0x9d, 0x37, 0xef, 0xbc, 0x83, 0x8d, 0x43, 0x69, 0x67, 0xc0, 0x89, 0xbb,
	0xf8, 0x3e, 0xc7, 0x6c, 0x81, 0x2d, 0x63, 0xde, 0x16, 0xdb, 0x85, 0x8a, 0xcf, 0x89, 0xdb, 0x66,
	0xc7, 0xea, 0x36, 0x0e, 0xa0, 0xc7, 0x13, 0xd1, 0x53, 0xc5, 0x90, 0xb8, 0xb3, 0x0b, 0x2b, 0xba,
	0x27, 0x4a, 0xb4, 0x54, 0x13, 0xe7, 0xbb, 0x01, 0x6b, 0xaf, 0x45, 0x46, 0xb3, 0x1b, 0x6f, 0x42,
	0x35, 0x10, 0xa1, 0x20, 0x4d, 0x53, 0x0b, 0xd6, 0x82, 0x5a, 0x3c, 0x1e, 0x67, 0x48, 0xba, 0x4d,
	0x7a, 0x55, 0x5c, 0x5c, 0x46, 0x3c, 0x25, 0xcf, 0xe7, 0xa4, 0x72, 0xba, 0xe3, 0xe2, 0x24, 0x7b,
	0xc0, 0x09, 0xd9, 0x63, 0x58, 0xc6, 0xc8, 0x57, 0x83, 0x95, 0x3b, 0x07, 0x97, 0x30, 0xf2, 0xe5,
	0x98, 0x0d, 0x4b, 0x63, 0x11, 0x10, 0xa6, 0x45, 0x98, 0x56, 0xb7, 0xee, 0x4e, 0x96, 0xce, 0x2f,
	0x03, 0xec, 0x89, 0x9b, 0xa3, 0x38, 0x1d, 0xc8, 0xbe, 0x4f, 0x6c, 0x6d, 0xcf, 0xfe, 0x11, 0xca,
	0xda, 0x14, 0x98, 0x9a, 0x36, 0x17, 0x9b, 0xb6, 0xfe, 0x60, 0xba, 0xf2, 0x50, 0xd3, 0xd5, 0x07,
	0x99, 0xae, 0xdd, 0x34, 0x3d, 0x84, 0xf5, 0xe9, 0x0d, 0xea, 0xd7, 0x60, 0x0f, 0x1a, 0x14, 0x13,
	0x0f, 0xbc, 0x51, 0x9c, 0x47, 0x93, 0x8b, 0x04, 0x09, 0x1d, 0x16, 0x08, 0xfb, 0x1f, 0x6a, 0x29,
	0x66, 0x79, 0x40, 0xba, 0x39, 0x7f, 0xc9, 0xe6, 0x94, 0x5f, 0x15, 0x57, 0x93, 0x0e, 0xbe, 0x5a,
	0xba, 0x47, 0xa7, 0x98, 0x16, 0x89, 0xb1, 0x13, 0xa8, 0xa9, 0xc6, 0xb2, 0x96, 0x9c, 0x9c, 0xab,
	0x6f, 0xbb, 0x35, 0xe7, 0xea, 0x79, 0xf1, 0x86, 0x39, 0x9b, 0x9f, 0x7e, 0xfc, 0xfc, 0x6c, 0x36,
	0x9d, 0xba, 0x7c, 0x1b, 0x8b, 0x92, 0x3e, 0x35, 0xf6, 0xd9, 0x31, 0x58, 0xc7, 0x48, 0x6c, 0x63,
	0xa6, 0xc0, 0x5a, 0x67, 0xf1, 0xc9, 0x9c, 0x96, 0x94, 0x59, 0x67, 0xcd, 0x6b, 0x99, 0xfe, 0xa5,
	0xf0, 0xaf, 0xd8, 0x11, 0x54, 0x8a, 0x34, 0xd8, 0xa6, 0x1c, 0x2b, 0x55, 0x5b, 0x8b, 0x95, 0xe3,
	0x72, 0x36, 0xa4, 0x58, 0x83, 0x4d, 0xcf, 0xc4, 0x02, 0x58, 0x2d, 0x68, 0xd7, 0x2d, 0x62, 0x3b,
	0x37, 0x46, 0xcb, 0xed, 0xba, 0x4d, 0xf9, 0x5f, 0xa9, 0xbc, 0xc7, 0x76, 0x94, 0xb2, 0x1c, 0xc9,
	0xfa, 0x97, 0xd7, 0xbd, 0xbb, 0x52, 0xbb, 0xbd, 0x82, 0xda, 0x00, 0x03, 0x24, 0x5c, 0x94, 0xc0,
	0x6d, 0x49, 0xea, 0x08, 0xf6, 0x4b, 0x11, 0x0c, 0x6b, 0x92, 0xf7, 0xe8, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc2, 0xc4, 0xa9, 0x80, 0x96, 0x06, 0x00, 0x00,
}
